=== vivekbhardwaj/HybridAutomationFramework/fb/target/classes/xsd/pageData.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.fbtest.com/pageData" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="pageData">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="configuration">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="username" type="xs:string" />
              <xs:element name="password" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== vivekbhardwaj/HybridAutomationFramework/fb/data/EnvironmentOne/PageData.xml
<?xml version="1.0" encoding="UTF-8"?>
<pageData xmlns="http://www.fbtest.com/pageData"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="../../src/test/resources/xsd/pageData.xsd ">
          
<configuration id='config0'>
  <username>mno</username>
  <password>pqr</password>
</configuration>
<configuration id='config1'>
  <username>xyz</username>
  <password>wxy</password>
</configuration>
<configuration id='config2'>
  <username>abc</username>
  <password>def</password>
</configuration>
</pageData>
